import type { Lead } from '../types/lead'

export const MOCK_LEADS: Lead[] = [
  {
    id: 'mock-1',
    companyName: 'Alt Security',
    address: '—',
    city: 'Salem',
    state: 'MA',
    sector: 'Professional, Scientific, and Technical Services',
    selector: 'Security Systems Services',
    phone: '',
    website: '',
    status: 'not_contacted',
    priority: 'medium',
    contactName: '',
    contactRole: '',
    contactEmail: '',
    lastContactedAt: '',
    nextFollowUpAt: '',
    notes: '',
    qualification: {
      hasWebsite: false,
      websiteNeedsWork: false,
      accessibilityOpportunity: false,
      seoOpportunity: false,
      aeoOpportunity: false,
      decisionMakerFound: false,
    },
    sourceUrl: '',
    createdAt: '2025-05-01T00:00:00.000Z',
    updatedAt: '2025-05-01T00:00:00.000Z',
  },
  {
    id: 'mock-2',
    companyName: 'Aquafisk Inc',
    address: 'Colonial Rd #28',
    city: 'Salem',
    state: 'MA',
    sector: 'Manufacturing',
    selector: 'Food Manufacturing',
    phone: '',
    website: '',
    status: 'called',
    priority: 'high',
    contactName: '',
    contactRole: '',
    contactEmail: '',
    lastContactedAt: '2025-05-20T00:00:00.000Z',
    nextFollowUpAt: '2025-05-28T00:00:00.000Z',
    notes: 'Spoke with front desk. Follow up with owner.',
    qualification: {
      hasWebsite: false,
      websiteNeedsWork: true,
      accessibilityOpportunity: true,
      seoOpportunity: true,
      aeoOpportunity: false,
      decisionMakerFound: false,
    },
    sourceUrl: '',
    createdAt: '2025-05-01T00:00:00.000Z',
    updatedAt: '2025-05-20T00:00:00.000Z',
  },
  {
    id: 'mock-3',
    companyName: 'Aquamarine Inc',
    address: 'Colonial Rd #206',
    city: 'Salem',
    state: 'MA',
    sector: 'Manufacturing',
    selector: 'Machinery Manufacturing',
    phone: '',
    website: '',
    status: 'follow_up',
    priority: 'medium',
    contactName: '',
    contactRole: '',
    contactEmail: '',
    lastContactedAt: '2025-05-16T00:00:00.000Z',
    nextFollowUpAt: '2025-05-30T00:00:00.000Z',
    notes: 'Interested in SEO audit. Call back end of month.',
    qualification: {
      hasWebsite: true,
      websiteNeedsWork: true,
      accessibilityOpportunity: false,
      seoOpportunity: true,
      aeoOpportunity: false,
      decisionMakerFound: true,
    },
    sourceUrl: '',
    createdAt: '2025-05-01T00:00:00.000Z',
    updatedAt: '2025-05-16T00:00:00.000Z',
  },
  {
    id: 'mock-4',
    companyName: 'ATC Security',
    address: 'Cavendish Cir',
    city: 'Salem',
    state: 'MA',
    sector: 'Professional, Scientific, and Technical Services',
    selector: 'Security Systems Services',
    phone: '',
    website: '',
    status: 'interested',
    priority: 'high',
    contactName: '',
    contactRole: '',
    contactEmail: '',
    lastContactedAt: '2025-05-18T00:00:00.000Z',
    nextFollowUpAt: '2025-05-27T00:00:00.000Z',
    notes: 'Spoke with manager. Very interested in website redesign.',
    qualification: {
      hasWebsite: true,
      websiteNeedsWork: true,
      accessibilityOpportunity: true,
      seoOpportunity: true,
      aeoOpportunity: true,
      decisionMakerFound: true,
    },
    sourceUrl: '',
    createdAt: '2025-05-01T00:00:00.000Z',
    updatedAt: '2025-05-18T00:00:00.000Z',
  },
  {
    id: 'mock-5',
    companyName: 'Brito Refrigeration Inc',
    address: 'Canal St #4',
    city: 'Salem',
    state: 'MA',
    sector: 'Construction',
    selector: 'HVAC and Refrigeration',
    phone: '',
    website: '',
    status: 'not_contacted',
    priority: 'low',
    contactName: '',
    contactRole: '',
    contactEmail: '',
    lastContactedAt: '',
    nextFollowUpAt: '',
    notes: '',
    qualification: {
      hasWebsite: false,
      websiteNeedsWork: false,
      accessibilityOpportunity: false,
      seoOpportunity: false,
      aeoOpportunity: false,
      decisionMakerFound: false,
    },
    sourceUrl: '',
    createdAt: '2025-05-01T00:00:00.000Z',
    updatedAt: '2025-05-01T00:00:00.000Z',
  },
  {
    id: 'mock-6',
    companyName: 'Circle of Stiches',
    address: 'Wharf St',
    city: 'Salem',
    state: 'MA',
    sector: 'Retail Trade',
    selector: 'Other Retail',
    phone: '',
    website: '',
    status: 'called',
    priority: 'medium',
    contactName: '',
    contactRole: '',
    contactEmail: '',
    lastContactedAt: '2025-05-19T00:00:00.000Z',
    nextFollowUpAt: '2025-06-02T00:00:00.000Z',
    notes: '',
    qualification: {
      hasWebsite: false,
      websiteNeedsWork: false,
      accessibilityOpportunity: false,
      seoOpportunity: true,
      aeoOpportunity: false,
      decisionMakerFound: false,
    },
    sourceUrl: '',
    createdAt: '2025-05-01T00:00:00.000Z',
    updatedAt: '2025-05-19T00:00:00.000Z',
  },
  {
    id: 'mock-7',
    companyName: 'Creative Metals',
    address: 'Industrial Dr',
    city: 'Salem',
    state: 'MA',
    sector: 'Manufacturing',
    selector: 'Metal Fabrication',
    phone: '',
    website: '',
    status: 'not_contacted',
    priority: 'low',
    contactName: '',
    contactRole: '',
    contactEmail: '',
    lastContactedAt: '',
    nextFollowUpAt: '',
    notes: '',
    qualification: {
      hasWebsite: false,
      websiteNeedsWork: false,
      accessibilityOpportunity: false,
      seoOpportunity: false,
      aeoOpportunity: false,
      decisionMakerFound: false,
    },
    sourceUrl: '',
    createdAt: '2025-05-01T00:00:00.000Z',
    updatedAt: '2025-05-01T00:00:00.000Z',
  },
  {
    id: 'mock-8',
    companyName: 'Harbor Logistics',
    address: 'Portland St',
    city: 'Salem',
    state: 'MA',
    sector: 'Transportation',
    selector: 'Freight & Logistics',
    phone: '',
    website: '',
    status: 'proposal_sent',
    priority: 'high',
    contactName: '',
    contactRole: '',
    contactEmail: '',
    lastContactedAt: '2025-05-21T00:00:00.000Z',
    nextFollowUpAt: '2025-06-05T00:00:00.000Z',
    notes: 'Sent proposal for full site rebuild + SEO package.',
    qualification: {
      hasWebsite: true,
      websiteNeedsWork: true,
      accessibilityOpportunity: true,
      seoOpportunity: true,
      aeoOpportunity: true,
      decisionMakerFound: true,
    },
    sourceUrl: '',
    createdAt: '2025-05-21T00:00:00.000Z',
    updatedAt: '2025-05-21T00:00:00.000Z',
  },
]
