import type { Lead } from '../types/lead'
import { applyDefaults } from './leadValidation'

function mockLead(partial: Partial<Lead>): Lead {
  return applyDefaults(partial)
}

export const MOCK_LEADS: Lead[] = [
  mockLead({
    id: 'mock-1',
    companyName: 'Alt Security',
    address: '—',
    city: 'Salem',
    state: 'MA',
    sector: 'Professional, Scientific, and Technical Services',
    status: 'not_contacted',
    priority: 'medium',
    createdAt: '2025-05-01T00:00:00.000Z',
    updatedAt: '2025-05-01T00:00:00.000Z',
  }),
  mockLead({
    id: 'mock-2',
    companyName: 'Aquafisk Inc',
    address: 'Colonial Rd #28',
    city: 'Salem',
    state: 'MA',
    sector: 'Manufacturing',
    status: 'called',
    priority: 'high',
    lastContactedAt: '2025-05-20T00:00:00.000Z',
    nextFollowUpAt: '2025-05-28T00:00:00.000Z',
    notes: 'Spoke with front desk. Follow up with owner.',
    qualification: {
      hasWebsite: false,
      websiteNeedsWork: true,
      accessibilityOpportunity: true,
      seoOpportunity: true,
      aeoOpportunity: false,
      decisionMakerFound: false,
    },
    createdAt: '2025-05-01T00:00:00.000Z',
    updatedAt: '2025-05-20T00:00:00.000Z',
  }),
  mockLead({
    id: 'mock-3',
    companyName: 'Aquamarine Inc',
    address: 'Colonial Rd #206',
    city: 'Salem',
    state: 'MA',
    sector: 'Manufacturing',
    website: 'https://aquamarine.example.com',
    status: 'follow_up',
    priority: 'medium',
    lastContactedAt: '2025-05-16T00:00:00.000Z',
    nextFollowUpAt: '2025-05-30T00:00:00.000Z',
    notes: 'Interested in SEO audit. Call back end of month.',
    qualification: {
      hasWebsite: true,
      websiteNeedsWork: true,
      accessibilityOpportunity: false,
      seoOpportunity: true,
      aeoOpportunity: false,
      decisionMakerFound: true,
    },
    createdAt: '2025-05-01T00:00:00.000Z',
    updatedAt: '2025-05-16T00:00:00.000Z',
  }),
  mockLead({
    id: 'mock-4',
    companyName: 'ATC Security',
    address: 'Cavendish Cir',
    city: 'Salem',
    state: 'MA',
    sector: 'Professional, Scientific, and Technical Services',
    website: 'https://atcsecurity.example.com',
    status: 'interested',
    priority: 'high',
    lastContactedAt: '2025-05-18T00:00:00.000Z',
    nextFollowUpAt: '2025-05-27T00:00:00.000Z',
    notes: 'Spoke with manager. Very interested in website redesign.',
    qualification: {
      hasWebsite: true,
      websiteNeedsWork: true,
      accessibilityOpportunity: true,
      seoOpportunity: true,
      aeoOpportunity: true,
      decisionMakerFound: true,
    },
    createdAt: '2025-05-01T00:00:00.000Z',
    updatedAt: '2025-05-18T00:00:00.000Z',
  }),
  mockLead({
    id: 'mock-5',
    companyName: 'Brito Refrigeration Inc',
    address: 'Canal St #4',
    city: 'Salem',
    state: 'MA',
    sector: 'Construction',
    status: 'not_contacted',
    priority: 'low',
    createdAt: '2025-05-01T00:00:00.000Z',
    updatedAt: '2025-05-01T00:00:00.000Z',
  }),
  mockLead({
    id: 'mock-6',
    companyName: 'Circle of Stiches',
    address: 'Wharf St',
    city: 'Salem',
    state: 'MA',
    sector: 'Retail Trade',
    status: 'called',
    priority: 'medium',
    lastContactedAt: '2025-05-19T00:00:00.000Z',
    nextFollowUpAt: '2025-06-02T00:00:00.000Z',
    qualification: {
      hasWebsite: false,
      websiteNeedsWork: false,
      accessibilityOpportunity: false,
      seoOpportunity: true,
      aeoOpportunity: false,
      decisionMakerFound: false,
    },
    createdAt: '2025-05-01T00:00:00.000Z',
    updatedAt: '2025-05-19T00:00:00.000Z',
  }),
  mockLead({
    id: 'mock-7',
    companyName: 'Creative Metals',
    address: 'Industrial Dr',
    city: 'Salem',
    state: 'MA',
    sector: 'Manufacturing',
    status: 'not_contacted',
    priority: 'low',
    createdAt: '2025-05-01T00:00:00.000Z',
    updatedAt: '2025-05-01T00:00:00.000Z',
  }),
  mockLead({
    id: 'mock-8',
    companyName: 'Harbor Logistics',
    address: 'Portland St',
    city: 'Salem',
    state: 'MA',
    sector: 'Transportation',
    website: 'https://harborlogistics.example.com',
    status: 'proposal_sent',
    priority: 'high',
    lastContactedAt: '2025-05-21T00:00:00.000Z',
    nextFollowUpAt: '2025-06-05T00:00:00.000Z',
    notes: 'Sent proposal for full site rebuild + SEO package.',
    qualification: {
      hasWebsite: true,
      websiteNeedsWork: true,
      accessibilityOpportunity: true,
      seoOpportunity: true,
      aeoOpportunity: true,
      decisionMakerFound: true,
    },
    createdAt: '2025-05-21T00:00:00.000Z',
    updatedAt: '2025-05-21T00:00:00.000Z',
  }),
]
